import json
import os
import re

print("Loading data.js...")
with open('c:/Users/AlFurqan/Desktop/ahmedsaeedss.github.io-main/data.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Parse the JSON part
json_start = content.find('[')
json_end = content.rfind(']') + 1
quiz_data = json.loads(content[json_start:json_end])

def get_category_idx(name):
    for i, main_cat in enumerate(quiz_data):
        if "subcategories" in main_cat:
            for j, sub_cat in enumerate(main_cat["subcategories"]):
                if sub_cat["category"] == name:
                    return i, j
    return -1, -1

questions_empires = [
    {"q": "Which Caliphate immediately succeeded the Prophet Muhammad (PBUH)?", "options": ["Umayyad", "Abbasid", "Rashidun", "Ottoman"], "answer": 2, "explanation": "The Rashidun Caliphate was the first of the four major caliphates established after the death of the Prophet (PBUH)."},
    {"q": "Who was the founder of the Umayyad Caliphate?", "options": ["Muawiya I", "Yazid I", "Abd al-Malik", "Walid I"], "answer": 0, "explanation": "Muawiya I established the Umayyad Caliphate in 661 CE."},
    {"q": "What was the capital of the Abbasid Caliphate for most of its history?", "options": ["Damascus", "Baghdad", "Cairo", "Cordoba"], "answer": 1, "explanation": "Baghdad was founded in 762 CE and served as the capital of the Abbasid Caliphate."},
    {"q": "Which Islamic empire was established in Spain and Portugal?", "options": ["Fatimid Caliphate", "Al-Andalus", "Mamluk Sultanate", "Safavid Empire"], "answer": 1, "explanation": "Al-Andalus was the Muslim-ruled area of the Iberian Peninsula."},
    {"q": "Who was the longest-reigning sultan of the Ottoman Empire?", "options": ["Mehmed the Conqueror", "Selim I", "Suleiman the Magnificent", "Abdul Hamid II"], "answer": 2, "explanation": "Suleiman the Magnificent ruled from 1520 to 1566."},
    {"q": "Which empire was known for the 'Gunpowder Empires' along with the Ottomans and Mughals?", "options": ["Mamluk", "Ayyubid", "Safavid", "Seljuk"], "answer": 2, "explanation": "The Safavid Empire was one of the three Islamic Gunpowder Empires."},
    {"q": "The Fatimid Caliphate was primarily based in which modern-day region?", "options": ["Iraq", "Egypt", "Spain", "Persia"], "answer": 1, "explanation": "The Fatimid Caliphate was an Ismaili Shia caliphate centered in Egypt."},
    {"q": "Who founded the Ayyubid Dynasty?", "options": ["Nur ad-Din", "Al-Kamil", "Saladin (Salah ad-Din)", "Baybars"], "answer": 2, "explanation": "Saladin founded the Ayyubid dynasty and led the Muslim opposition to the European Crusaders."},
    {"q": "The Mamluk Sultanate successfully defeated which invading empire at the Battle of Ain Jalut?", "options": ["Crusaders", "Byzantines", "Mongols", "Ottomans"], "answer": 2, "explanation": "The Mamluks handed the Mongol Empire its first major defeat at Ain Jalut in 1260."},
    {"q": "Which Mughal Emperor built the Taj Mahal?", "options": ["Akbar", "Jahangir", "Shah Jahan", "Aurangzeb"], "answer": 2, "explanation": "Shah Jahan commissioned the Taj Mahal in 1631 to house the tomb of his favorite wife, Mumtaz Mahal."},
    {"q": "Which city was conquered by Ottoman Sultan Mehmed II in 1453?", "options": ["Vienna", "Constantinople", "Belgrade", "Budapest"], "answer": 1, "explanation": "The capture of Constantinople marked the end of the Byzantine Empire."},
    {"q": "The Seljuk Empire was founded by which ethnic group?", "options": ["Arabs", "Persians", "Turks (Oghuz)", "Berbers"], "answer": 2, "explanation": "The Seljuks were a Turco-Persian Sunni Muslim empire originally from the Oghuz Turkish branch."},
    {"q": "During which caliphate did the Islamic Golden Age primarily flourish?", "options": ["Rashidun", "Umayyad", "Abbasid", "Ottoman"], "answer": 2, "explanation": "The Abbasid Caliphate oversaw a period of significant cultural, economic, and scientific flourishing."},
    {"q": "What was the official language of the Mughal Empire court?", "options": ["Arabic", "Turkish", "Persian", "Urdu"], "answer": 2, "explanation": "Persian was the official and court language of the Mughal Empire."},
    {"q": "Which Umayyad ruler initiated the construction of the Dome of the Rock?", "options": ["Muawiya I", "Abd al-Malik ibn Marwan", "Al-Walid I", "Umar II"], "answer": 1, "explanation": "Abd al-Malik commissioned the Dome of the Rock in Jerusalem, completed in 691 CE."},
    {"q": "The city of Cordoba in Al-Andalus reached its zenith under which ruler?", "options": ["Tariq ibn Ziyad", "Abd al-Rahman I", "Abd al-Rahman III", "Al-Mansur"], "answer": 2, "explanation": "Abd al-Rahman III declared himself Caliph in 929, marking a golden age for Cordoba."},
    {"q": "Which empire established Shi'a Islam as its official religion, significantly shaping modern Iran?", "options": ["Seljuk", "Safavid", "Mughal", "Ghaznavid"], "answer": 1, "explanation": "The Safavid Empire made Twelver Shi'ism the official religion of their empire."},
    {"q": "Which dynasty ruled from Cairo and was known for its famous university, Al-Azhar?", "options": ["Ayyubid", "Mamluk", "Fatimid", "Tulunid"], "answer": 2, "explanation": "The Fatimid Caliphate founded Cairo and established the Al-Azhar Mosque and University."},
    {"q": "Who was the founder of the Mughal Empire?", "options": [" बाबर (Babur)", "Humayun", "Akbar", "Shah Jahan"], "answer": 0, "explanation": "Babur founded the Mughal Empire after his victory at the First Battle of Panipat in 1526."},
    {"q": "The Abbasid Caliphate was eventually destroyed by the sack of Baghdad in 1258. Who led the sack?", "options": ["Timur", "Genghis Khan", "Hulagu Khan", "Saladin"], "answer": 2, "explanation": "Hulagu Khan, a Mongol ruler, sacked Baghdad, functionally ending the Abbasid Caliphate."},
    {"q": "Which Islamic leader retook Jerusalem from the Crusaders in 1187?", "options": ["Tariq ibn Ziyad", "Nur ad-Din", "Saladin (Salah ad-Din)", "Baybars"], "answer": 2, "explanation": "Saladin captured Jerusalem after the Battle of Hattin."},
    {"q": "The Ghaznavid Empire, known for its conquests in the Indian subcontinent, was centered in which modern country?", "options": ["Iran", "Afghanistan", "Pakistan", "India"], "answer": 1, "explanation": "The Ghaznavid Empire was centered in Ghazni, in modern-day Afghanistan."},
    {"q": "Which Ottoman ruler is known as 'The Lawgiver' in the Islamic world?", "options": ["Selim I", "Mehmed II", "Suleiman the Magnificent", "Murad IV"], "answer": 2, "explanation": "Suleiman the Magnificent is known as 'Kanuni' (the Lawmaker) in the East."},
    {"q": "The Battle of Tours (732 CE) halted the advance of which Islamic empire into Western Europe?", "options": ["Rashidun", "Umayyad", "Abbasid", "Fatimid"], "answer": 1, "explanation": "The Umayyad advance into Gaul (France) was stopped at the Battle of Tours."},
    {"q": "Which dynasty ruled the Emirate of Sicily from the 9th to 11th centuries?", "options": ["Aghlabids/Kalbids", "Fatimids", "Umayyads", "Almoravids"], "answer": 0, "explanation": "The Aghlabids conquered Sicily, and later the Kalbids ruled it as an emirate."},
    {"q": "The Almohad Caliphate, a North African and Iberian empire, was founded by which religious movement?", "options": ["Ash'ari", "Mu'tazila", "Zahiri", "Ibn Tumart's reformist movement"], "answer": 3, "explanation": "Ibn Tumart founded the Almohad movement, which emphasized strict monotheism."},
    {"q": "Which empire was known for the highly trained slave-soldiers known as 'Mamluks'?", "options": ["Ottoman Empire", "Safavid Empire", "Mamluk Sultanate", "Mughal Empire"], "answer": 2, "explanation": "The Mamluk Sultanate of Egypt and the Levant was ruled by a military caste of former slaves."},
    {"q": "Who was the last Caliph of the Ottoman Empire?", "options": ["Mehmed VI", "Abdulmejid II", "Abdul Hamid II", "Mustafa Kemal"], "answer": 1, "explanation": "Abdulmejid II was the last Caliph before the Caliphate was abolished in 1924."},
    {"q": "The famous traveler Ibn Battuta visited and documented many Islamic empires. Which empire was ruling India during his visit?", "options": ["Mughal Empire", "Delhi Sultanate", "Ghaznavid Empire", "Ghurid Dynasty"], "answer": 1, "explanation": "He visited during the reign of Muhammad bin Tughluq of the Delhi Sultanate."},
    {"q": "Which architectural masterpiece was built during the reign of the Umayyad caliph Al-Walid I in Damascus?", "options": ["Dome of the Rock", "Al-Aqsa Mosque", "Umayyad Mosque", "Great Mosque of Cordoba"], "answer": 2, "explanation": "The Great Mosque of Damascus, also known as the Umayyad Mosque, was completed in 715 CE."},
    {"q": "The term 'House of Wisdom' (Bayt al-Hikmah) is associated with which caliphate?", "options": ["Umayyad", "Abbasid", "Fatimid", "Rashidun"], "answer": 1, "explanation": "The House of Wisdom was a major intellectual center during the Abbasid Caliphate in Baghdad."},
    {"q": "Which empire utilized the 'Janissary' elite infantry units?", "options": ["Seljuk", "Mamluk", "Safavid", "Ottoman"], "answer": 3, "explanation": "The Janissaries were the elite infantry units from the Ottoman household troops."},
    {"q": "The Mughal Emperor Akbar is famous for his policy of?", "options": ["Strict religious orthodoxy", "Religious tolerance and syncretism", "Isolationism", "Vast naval expansion"], "answer": 1, "explanation": "Akbar promoted religious tolerance and famously established the 'Din-i-Ilahi'."],
    {"q": "Which battle functionally ended the Mamluk Sultanate and brought Egypt under Ottoman control?", "options": ["Battle of Ankara", "Battle of Chaldiran", "Battle of Ridaniya", "Battle of Lepanto"], "answer": 2, "explanation": "The Battle of Ridaniya in 1517 marked the fall of the Mamluk Sultanate to the Ottomans."},
    {"q": "The Safavid capital was moved to which beautiful city by Shah Abbas I?", "options": ["Tabriz", "Qazvin", "Isfahan", "Tehran"], "answer": 2, "explanation": "Shah Abbas I moved the capital to Isfahan and initiated massive architectural projects."},
    {"q": "Which Muslim dynasty was the first to establish an empire in the Indian subcontinent (Delhi Sultanate)?", "options": ["Mamluk (Slave) Dynasty", "Khilji Dynasty", "Tughlaq Dynasty", "Lodi Dynasty"], "answer": 0, "explanation": "The Mamluk (Slave) Dynasty, founded by Qutb ud-Din Aibak, was the first dynasty of the Delhi Sultanate."},
    {"q": "Who was the central figure of the Mahdist State in Sudan, which resisted British and Egyptian rule in the late 19th century?", "options": ["Omar Mukhtar", "Muhammad Ahmad", "Usman dan Fodio", "Abd al-Qadir"], "answer": 1, "explanation": "Muhammad Ahmad proclaimed himself the Mahdi and led a successful revolt against Ottoman-Egyptian rule."},
    {"q": "The Sokoto Caliphate, a massive Islamic state in West Africa, was founded by?", "options": ["Mansa Musa", "Askia the Great", "Usman dan Fodio", "Samori Ture"], "answer": 2, "explanation": "Usman dan Fodio led a jihad that resulted in the creation of the Sokoto Caliphate in 1804."},
    {"q": "Which empire was ruled by the 'Khwarazmian' dynasty before being destroyed by Genghis Khan?", "options": ["Khwarazmian Empire", "Seljuk Empire", "Ghaznavid Empire", "Samanid Empire"], "answer": 0, "explanation": "The Khwarazmian Empire controlled a vast area of Central Asia and Iran before the Mongol invasion."},
    {"q": "The 'Tanzimat' were a series of impactful reforms carried out in which Islamic empire?", "options": ["Mughal Empire", "Safavid Empire", "Ottoman Empire", "Qajar Iran"], "answer": 2, "explanation": "The Tanzimat reform era (1839–1876) aimed to modernize the Ottoman Empire."},
    {"q": "Which Muslim general conquered the Iberian Peninsula in 711 CE?", "options": ["Amr ibn al-Aas", "Tariq ibn Ziyad", "Khalid ibn al-Walid", "Uqba ibn Nafi"], "answer": 1, "explanation": "Tariq ibn Ziyad led the initial Umayyad conquest of Hispania."},
    {"q": "The city of Samarra served as the capital for which caliphate for about six decades?", "options": ["Umayyad", "Abbasid", "Fatimid", "Ayyubid"], "answer": 1, "explanation": "The Abbasid capital was temporarily moved to Samarra from 836 to 892 CE."},
    {"q": "The 'Reconquista' was a centuries-long effort by Christian states to expel Muslims from?", "options": ["The Balkans", "Sicily", "The Iberian Peninsula", "Anatolia"], "answer": 2, "explanation": "The Reconquista culminated in the fall of Granada in 1492, ending Islamic rule in Iberia."},
    {"q": "Who was the first caliph of the Umayyad Caliphate of Cordoba?", "options": ["Abd al-Rahman I", "Abd al-Rahman II", "Abd al-Rahman III", "Al-Hakam II"], "answer": 2, "explanation": "Abd al-Rahman III assumed the title of Caliph in 929 CE."},
    {"q": "The famous 'Blue Mosque' (Sultan Ahmed Mosque) was built during which empire?", "options": ["Mamluk", "Safavid", "Mughal", "Ottoman"], "answer": 3, "explanation": "It was constructed between 1609 and 1616 during the rule of Ahmed I in the Ottoman Empire."},
    {"q": "Which dynasty ruled Iran immediately following the Safavids?", "options": ["Samanids", "Zand Dynasty", "Afsharid Dynasty", "Qajar Dynasty"], "answer": 2, "explanation": "Nader Shah founded the Afsharid dynasty after the collapse of the Safavids."},
    {"q": "The Ayyubid Sultanate was eventually overthrown by their own slave-soldiers, leading to the rise of which empire?", "options": ["Fatimid Caliphate", "Mamluk Sultanate", "Ottoman Empire", "Seljuk Empire"], "answer": 1, "explanation": "The Mamluks took over power from the Ayyubids in Egypt."},
    {"q": "What was the capital of the Fatimid Caliphate before it was moved to Cairo?", "options": ["Mahdia", "Damascus", "Baghdad", "Marrakesh"], "answer": 0, "explanation": "The Fatimids established their first capital at Mahdia in modern-day Tunisia."},
    {"q": "The title 'Amir al-Mu'minin' translates to?", "options": ["Shadow of God", "Commander of the Faithful", "Sword of Islam", "Servant of the Two Sanctuaries"], "answer": 1, "explanation": "It is an Arabic style and title of the supreme leader of the Islamic community."},
    {"q": "At its greatest extent, the Ottoman Empire spanned across which three continents?", "options": ["Europe, Asia, Africa", "Europe, Asia, Australia", "Asia, Africa, South America", "Asia, Africa, Antarctica"], "answer": 0, "explanation": "The Ottoman Empire held territories in Southeastern Europe, Western Asia, and Northern Africa."}
]

questions_sharia = [
    {"q": "What are the two primary sources of Islamic Sharia Law?", "options": ["Quran and Qiyas", "Quran and Sunnah", "Sunnah and Ijma", "Ijma and Qiyas"], "answer": 1, "explanation": "The Quran and the Sunnah (teachings/practices of the Prophet) are the foundational sources of Sharia."},
    {"q": "The consensus of Islamic scholars on a particular issue is called?", "options": ["Qiyas", "Ijtihad", "Ijma", "Fatwa"], "answer": 2, "explanation": "Ijma refers to the consensus or agreement of Muslim scholars on a point of Islamic law."},
    {"q": "What is the term for 'analogical reasoning' in Islamic jurisprudence?", "options": ["Ijma", "Qiyas", "Urf", "Istihsan"], "answer": 1, "explanation": "Qiyas is the process of deductive analogy to address new situations based on previously established rulings."},
    {"q": "Which of the following is NOT one of the four main Sunni schools of jurisprudence (Madhahib)?", "options": ["Hanafi", "Maliki", "Zaydi", "Shafi'i"], "answer": 2, "explanation": "Zaydi is a Shia school. The four main Sunni schools are Hanafi, Maliki, Shafi'i, and Hanbali."},
    {"q": "Who is the founder of the Hanafi school of thought?", "options": ["Imam Malik", "Imam Abu Hanifa", "Imam Al-Shafi'i", "Imam Ahmad bin Hanbal"], "answer": 1, "explanation": "Nu'man ibn Thabit, known as Imam Abu Hanifa, founded the Hanafi school."},
    {"q": "The independent legal reasoning by an Islamic scholar is referred to as?", "options": ["Taqlid", "Ijtihad", "Tafsir", "Tajweed"], "answer": 1, "explanation": "Ijtihad is an Islamic legal term referring to independent reasoning or the thorough exertion of a jurist's mental faculty."},
    {"q": "An action that is obligatory and its omission is punishable in Islam is called?", "options": ["Sunnah", "Mustahab", "Fard (Wajib)", "Mubah"], "answer": 2, "explanation": "Fard represents an absolute obligation, like the five daily prayers."},
    {"q": "An action that is strictly prohibited in Islam is termed?", "options": ["Makruh", "Haram", "Mubah", "Fard"], "answer": 1, "explanation": "Haram refers to purely forbidden acts, such as consuming alcohol or pork."},
    {"q": "An action that is disliked but not strictly forbidden is called?", "options": ["Haraam", "Makruh", "Mubaah", "Sunnah"], "answer": 1, "explanation": "Makruh denotes a disliked or offensive act, which is better to avoid but does not incur a sin if performed."},
    {"q": "An action that is permissible, bringing neither reward nor punishment, is termed?", "options": ["Mubah / Halal", "Makruh", "Mustahab", "Fard"], "answer": 0, "explanation": "Mubah refers to an action which is indifferent—neither ordered nor prohibited."},
    {"q": "An action that is recommended and brings reward, but leaving it incurs no punishment, is?", "options": ["Fard", "Mustahab / Sunnah / Mandub", "Mubah", "Makruh"], "answer": 1, "explanation": "Mustahab or Mandub acts are highly encouraged (like voluntary prayers) but not obligatory."},
    {"q": "What is the term for a formal legal opinion given by a Mufti?", "options": ["Hadith", "Fatwa", "Tafsir", "Khutbah"], "answer": 1, "explanation": "A Fatwa is a non-binding legal opinion on a point of Islamic law given by a qualified jurist."},
    {"q": "The Islamic concept of 'Halal' means?", "options": ["Prohibited", "Permissible / Lawful", "Obligatory", "Disliked"], "answer": 1, "explanation": "Halal is an Arabic word meaning lawful or permitted."},
    {"q": "Which school of jurisprudence is predominant in Saudi Arabia?", "options": ["Hanafi", "Maliki", "Shafi'i", "Hanbali"], "answer": 3, "explanation": "The Hanbali school, specifically through Wahhabi influence, is dominant in Saudi Arabia."},
    {"q": "Which school of jurisprudence is primarily followed in North Africa (excluding Egypt)?", "options": ["Hanafi", "Maliki", "Shafi'i", "Hanbali"], "answer": 1, "explanation": "The Maliki school is predominant across North and West Africa."},
    {"q": "Which school of jurisprudence is widely followed in South Asia (Pakistan, India, Bangladesh)?", "options": ["Hanafi", "Maliki", "Shafi'i", "Hanbali"], "answer": 0, "explanation": "The Hanafi school is the most widely followed Madhhab in South Asia."},
    {"q": "The term 'Nikah' refers to what in Sharia?", "options": ["Divorce", "Marriage", "Inheritance", "Charity"], "answer": 1, "explanation": "Nikah is the Islamic term for the contract of marriage."},
    {"q": "The mandatory gift given by the groom to the bride upon marriage is called?", "options": ["Zakat", "Sadaqah", "Mahr", "Jizya"], "answer": 2, "explanation": "Mahr is a mandatory payment, in the form of money or possessions paid by the groom regarding the bride."},
    {"q": "What is the Islamic term for divorce initiated by the husband?", "options": ["Khula", "Talaq", "Iddah", "Faskh"], "answer": 1, "explanation": "Talaq refers to repudiation or divorce initiated by the husband."},
    {"q": "What is the Islamic term for divorce initiated by the wife?", "options": ["Talaq", "Khula", "Zihar", "Lian"], "answer": 1, "explanation": "Khula is the right of a woman in Islam to divorce and separate from her husband."},
    {"q": "The waiting period a woman must observe after divorce or the death of her husband is called?", "options": ["Mahr", "Nikah", "Iddah", "Wali"], "answer": 2, "explanation": "The Iddah applies after divorce or widowhood, during which she may not marry another man."},
    {"q": "In Islamic inheritance (Miras), what is a generally stated ratio between a son's and a daughter's share?", "options": ["Equal", "Son gets double", "Daughter gets double", "Son gets triple"], "answer": 1, "explanation": "Generally, a male heir inherits twice the share of a female heir of the same degree (e.g., son and daughter)."},
    {"q": "Under Islamic law, a testament or will (Wasiyyah) can only apply to a maximum of what portion of the estate?", "options": ["One-half", "One-third", "One-fourth", "One-tenth"], "answer": 1, "explanation": "A Muslim can bequeath up to one-third of their estate to non-heirs; the rest must follow fixed Sharia shares."},
    {"q": "The fixed punishments mandated in the Quran and Sunnah for specific crimes are called?", "options": ["Tazir", "Qisas", "Hudud", "Diyya"], "answer": 2, "explanation": "Hudud crimes (like theft, adultery, slander) have specific, fixed punishments in Sharia."},
    {"q": "Discretionary punishments decided by a judge for crimes not specified under Hudud or Qisas are termed?", "options": ["Hudud", "Qisas", "Tazir", "Kaffarah"], "answer": 2, "explanation": "Tazir punishments are applied at the discretion of the judge (Qadi) for offenses for which no specific punishment is decreed."},
    {"q": "The principle of 'eye for an eye' or equal retaliation in cases of murder or bodily harm is called?", "options": ["Hudud", "Qisas", "Tazir", "Zakat"], "answer": 1, "explanation": "Qisas allows equal retaliation, though forgiveness (sometimes for Diyya/blood money) is highly recommended."},
    {"q": "Financial compensation paid to the victim or heirs of a victim for murder or bodily harm is called?", "options": ["Zakat", "Mahr", "Diyya", "Jizya"], "answer": 2, "explanation": "Diyya, often translated as blood money, is compensation for injury or death."},
    {"q": "Riba is strictly forbidden in Islamic finance. What does Riba mean?", "options": ["Profit", "Usury / Interest", "Tax", "Charity"], "answer": 1, "explanation": "Riba commonly refers to interest charged on loans, which is strictly prohibited (Haram)."},
    {"q": "The concept of 'Gharar' in Islamic finance forbids?", "options": ["Interest", "Excessive uncertainty or risk", "Partnerships", "Trading gold"], "answer": 1, "explanation": "Transactions involving extreme uncertainty, speculation, or hazard (Gharar) are invalid."},
    {"q": "A charitable endowment established for a religious or public purpose is called a?", "options": ["Zakat", "Waqf", "Sukuk", "Takaful"], "answer": 1, "explanation": "Waqf is an inalienable charitable endowment under Islamic law, typically involving donating a building or plot of land."},
    {"q": "What is the required threshold of wealth for paying Zakat called?", "options": ["Sadaqah", "Nisab", "Khums", "Fitrana"], "answer": 1, "explanation": "Nisab is the minimum amount of wealth a Muslim must own before they are obliged to pay Zakat."},
    {"q": "What is the standard rate of Zakat on accumulated cash and trade goods?", "options": ["1.0%", "2.5%", "5.0%", "10.0%"], "answer": 1, "explanation": "The standard Zakat rate on liquid assets held for a lunar year is 2.5%."},
    {"q": "Which tax was historically levied on non-Muslim subjects (Dhimmis) living under a Muslim state in exchange for protection?", "options": ["Zakat", "Khums", "Ushr", "Jizya"], "answer": 3, "explanation": "Jizya was a per capita yearly taxation on non-Muslim subjects, who were exempt from military service and Zakat."},
    {"q": "A religious tax largely paid by Shia Muslims, consisting of one-fifth of certain types of income/booty, is called?", "options": ["Zakat", "Khums", "Jizya", "Ushr"], "answer": 1, "explanation": "Khums refers to a 20% Islamic tax levied on specific items like spoils of war and surplus income in Shia fiqh."},
    {"q": "The term 'Muamalat' refers to?", "options": ["Acts of worship", "Civic / Commercial transactions", "Penal law", "Inheritance"], "answer": 1, "explanation": "Muamalat covers the social, civic, and commercial dealings and transactions in Sharia."},
    {"q": "The term 'Ibadat' refers to?", "options": ["Civic laws", "Acts of worship", "Family laws", "Criminal laws"], "answer": 1, "explanation": "Ibadat encompasses rituals and acts of worship like prayer, fasting, and pilgrimage."},
    {"q": "What is 'Takaful' in the context of Islamic finance?", "options": ["Islamic banking", "Islamic insurance", "Islamic bonds", "Islamic charity"], "answer": 1, "explanation": "Takaful is a co-operative system of reimbursement or repayment in case of loss, compliant with Sharia (Islamic insurance)."},
    {"q": "What are 'Sukuk'?", "options": ["Islamic bonds", "Charity funds", "Zakat collectors", "Divorce decrees"], "answer": 0, "explanation": "Sukuk is the Arabic name for financial certificates, also commonly referred to as 'Sharia-compliant bonds'."},
    {"q": "In Islamic penal law, the crime of apostasy or leaving Islam is known as?", "options": ["Zina", "Riddah", "Sariqa", "Qazf"], "answer": 1, "explanation": "Riddah or Irtidad denotes the conscious rejection of Islam by someone who had been a Muslim."},
    {"q": "The crime of false accusation of unchastity or adultery is called?", "options": ["Zina", "Qazf", "Sariqa", "Hirabah"], "answer": 1, "explanation": "Qazf refers to a false allegation of unlawful intercourse, bringing a punishment under Hudud."},
    {"q": "Which term describes 'necessity' in Islamic law, where forbidden things may become permissible to save a life?", "options": ["Darurah", "Maslahah", "Urf", "Istishab"], "answer": 0, "explanation": "The principle of Darurah allows exceptions, such as eating prohibited food to prevent starvation."},
    {"q": "The concept of public interest or common good in Islamic legal reasoning is called?", "options": ["Darurah", "Maslahah Mursalah", "Ijtihad", "Taqlid"], "answer": 1, "explanation": "Maslahah represents considerations of public interest not specifically mentioned in primary texts."},
    {"q": "What does a 'Qadi' do?", "options": ["Issues fatwas", "Leads prayers", "Acts as a judge in a Sharia court", "Collects Zakat"], "answer": 2, "explanation": "A Qadi is the magistrate or judge of a Sharia court."},
    {"q": "The practice of 'following' or 'imitating' a qualified religious scholar without independent legal reasoning is called?", "options": ["Taqlid", "Ijtihad", "Tajdid", "Tafsir"], "answer": 0, "explanation": "Taqlid means following the legal decisions of a higher authority or Madhhab without questioning the deductive process."},
    {"q": "Who wrote 'Al-Muwatta', one of the earliest collections of Hadith and Islamic jurisprudence?", "options": ["Imam Abu Hanifa", "Imam Bukhari", "Imam Malik", "Imam Muslim"], "answer": 2, "explanation": "Imam Malik ibn Anas compiled Al-Muwatta."},
    {"q": "In Sharia, what is 'Kaffarah'?", "options": ["A reward", "Expiation or compensation for a broken rule", "A type of prayer", "A marriage contract"], "answer": 1, "explanation": "Kaffarah is a penalty or expiation (like feeding the poor) for violating certain religious duties, like breaking an oath or a fast."},
    {"q": "According to Sharia, eating the meat of an animal found already dead (Carrion/Maytah) is?", "options": ["Halal", "Haram", "Makruh", "Mustahab"], "answer": 1, "explanation": "Carrion is explicitly forbidden in the Quran, except for fish and locusts in some rulings."},
    {"q": "A contract where one party provides capital and the other provides expertise/labor, sharing profits, is called?", "options": ["Musharakah", "Mudarabah", "Murabahah", "Ijarah"], "answer": 1, "explanation": "Mudarabah is a partnership where one provides the funds and the other provides the work."},
    {"q": "What is 'Murabahah' in Islamic finance?", "options": ["A loan with interest", "A joint venture", "Cost-plus financing/sale", "Leasing"], "answer": 2, "explanation": "Murabahah is a sale where the seller explicitly mentions the cost incurred, and sells to the buyer with a known profit markup."},
    {"q": "What is 'Ijarah'?", "options": ["Sale contract", "Partnership", "Leasing/Rental contract", "Endowment"], "answer": 2, "explanation": "Ijarah is equivalent to a lease or rental agreement."}
]

questions_wife = [
    {"q": "How many wives did Prophet Muhammad (PBUH) have during his lifetime (collectively known as Mothers of Believers)?", "options": ["9", "11", "13", "15"], "answer": 1, "explanation": "It is generally agreed he had 11 marriages that were consummated, though he did not have them all at the same time."},
    {"q": "Who was the only wife the Prophet (PBUH) did not marry after she was previously married or widowed?", "options": ["Hazrat Khadija (RA)", "Hazrat Aisha (RA)", "Hazrat Hafsa (RA)", "Hazrat Sawda (RA)"], "answer": 1, "explanation": "Hazrat Aisha (RA) was the only virgin he married."},
    {"q": "Who suggested the marriage between Prophet Muhammad (PBUH) and Hazrat Khadija (RA)?", "options": ["Abu Talib", "Nafisa bint Munya", "Hazrat Hamza (RA)", "Hazrat Abu Bakr (RA)"], "answer": 1, "explanation": "Nafisa, a friend of Khadija, acted as an intermediary to suggest the match."},
    {"q": "Which wife of the Prophet (PBUH) passed away during his lifetime after Khadija (RA)?", "options": ["Hazrat Sawda (RA)", "Hazrat Zainab bint Khuzaima (RA)", "Hazrat Aisha (RA)", "Hazrat Hafsa (RA)"], "answer": 1, "explanation": "Zainab bint Khuzaima passed away only a few months after their marriage."},
    {"q": "Hazrat Khadija (RA) was previously married how many times before marrying the Prophet (PBUH)?", "options": ["Once", "Twice", "Three times", "Never"], "answer": 1, "explanation": "She had been married twice and was twice widowed before marrying the Prophet (PBUH)."},
    {"q": "What was the previous name of Hazrat Juwayriya (RA) before the Prophet (PBUH) changed it?", "options": ["Hind", "Barrah", "Zainab", "Asma"], "answer": 1, "explanation": "Her name was Barrah, which means 'pious'. The Prophet changed it to Juwayriya."},
    {"q": "Which wife of the Prophet (PBUH) was married to him by an explicit verse revealed in the Quran?", "options": ["Hazrat Aisha (RA)", "Hazrat Khadija (RA)", "Hazrat Zainab bint Jahsh (RA)", "Hazrat Safiyya (RA)"], "answer": 2, "explanation": "The marriage to Zainab bint Jahsh was commanded in Surah Al-Ahzab (33:37)."},
    {"q": "Who was the first wife of the Prophet (PBUH) to pass away after his own death?", "options": ["Hazrat Aisha (RA)", "Hazrat Zainab bint Jahsh (RA)", "Hazrat Sawda (RA)", "Hazrat Hafsa (RA)"], "answer": 1, "explanation": "Zainab bint Jahsh (RA) was the first widow to die after the Prophet's death, around 20 AH."},
    {"q": "With whom did the Prophet (PBUH) share his secret of the first revelation in the Cave of Hira immediately?", "options": ["Abu Bakr (RA)", "Ali (RA)", "Khadija (RA)", "Waraqa bin Naufal"], "answer": 2, "explanation": "He returned home to Khadija (RA) asking her to cover him and told her what happened."},
    {"q": "Which wife of the Prophet (PBUH) advised him during the Truce of Hudaibiya when the companions were initially reluctant to shave their heads?", "options": ["Hazrat Aisha (RA)", "Hazrat Umm Salama (RA)", "Hazrat Hafsa (RA)", "Hazrat Maymuna (RA)"], "answer": 1, "explanation": "Umm Salama (RA) intelligently advised him to go and shave his own head first, which prompted the companions to follow."},
    {"q": "Who was the former husband of Hazrat Umm Salama (RA)?", "options": ["Abu Salama (RA)", "Zaid bin Harithah", "Khunais bin Hudhafa", "Obaidullah bin Jahsh"], "answer": 0, "explanation": "She was married to Abu Salama, who died from injuries sustained at the Battle of Uhud."},
    {"q": "Hazrat Maria al-Qibtiyya (Maria the Copt), who bore the Prophet's son Ibrahim, was gifted to him by?", "options": ["The King of Abyssinia", "The Muqawqis of Egypt", "The Emperor of Rome", "The King of Persia"], "answer": 1, "explanation": "The Muqawqis, ruler of Alexandria, sent her as a gift."},
    {"q": "Which wife of the Prophet (PBUH) was known for her exceptional skill in leatherwork and tanning, using the earnings for charity?", "options": ["Hazrat Aisha (RA)", "Hazrat Zainab bint Jahsh (RA)", "Hazrat Safiyya (RA)", "Hazrat Sawda (RA)"], "answer": 1, "explanation": "Zainab bint Jahsh was highly skilled in manual crafts and gave the proceeds to the poor."},
    {"q": "Hazrat Hafsa (RA) was married to whom before the Prophet (PBUH)?", "options": ["Khunais bin Hudhafa", "Zaid bin Harithah", "Ubaydullah bin Jahsh", "Al-Nu'man"], "answer": 0, "explanation": "Her first husband, Khunais, sustained fatal wounds at Badr."},
    {"q": "Who was the brother of Hazrat Aisha (RA) who led her camel during the Battle of the Camel?", "options": ["Abd al-Rahman ibn Abu Bakr", "Muhammad ibn Abu Bakr", "Abdullah ibn Abu Bakr", "Asma bint Abu Bakr"], "answer": 0, "explanation": "It was Abdul Rahman, though Muhammad ibn Abu Bakr was on the opposing side of Ali."},
    {"q": "Which wife was accused in the 'Event of Ifk' (The Slander), leading to verses of exoneration in the Quran?", "options": ["Hazrat Khadija (RA)", "Hazrat Sawda (RA)", "Hazrat Aisha (RA)", "Hazrat Hafsa (RA)"], "answer": 2, "explanation": "Hazrat Aisha (RA) was falsely accused, and Allah revealed verses in Surah An-Nur clearing her name."},
    {"q": "Upon the marriage of which wife did the Prophet (PBUH) manumit 100 households of her tribe?", "options": ["Hazrat Juwayriya (RA)", "Hazrat Safiyya (RA)", "Hazrat Maymuna (RA)", "Hazrat Umm Salama (RA)"], "answer": 0, "explanation": "When he married Juwayriya, the Muslims released their prisoners from her tribe (Banu Mustaliq) out of respect."},
    {"q": "Hazrat Safiyya's (RA) original name before accepting Islam was?", "options": ["Safiyya", "Barrah", "Zainab", "Atekah"], "answer": 0, "explanation": "She was known as Safiyya, but she was the daughter of Huyayy bin Akhtab."},
    {"q": "Who was the maternal aunt of Khalid bin Waleed (RA) and married the Prophet (PBUH)?", "options": ["Hazrat Maymuna (RA)", "Hazrat Umm Salama (RA)", "Hazrat Safiyya (RA)", "Hazrat Zainab (RA)"], "answer": 0, "explanation": "Maymuna bint al-Harith was the aunt of Khalid bin Walid and Ibn Abbas."},
    {"q": "The Prophet (PBUH) married Hazrat Umm Habiba (RA) while she was in?", "options": ["Madinah", "Makkah", "Abyssinia", "Taif"], "answer": 2, "explanation": "The Najashi (King of Abyssinia) conducted the marriage ceremony on behalf of the Prophet (PBUH) while she was in exile there."},
    {"q": "Who was the father of Hazrat Umm Habiba (RA)?", "options": ["Abu Bakr", "Umar", "Abu Sufyan", "Abu Jahl"], "answer": 2, "explanation": "Her real name was Ramla, daughter of Abu Sufyan, a leader of the Quraish who later accepted Islam."},
    {"q": "Which wife gave up her 'turn' (day with the Prophet) to Hazrat Aisha (RA) in her old age to remain his wife?", "options": ["Hazrat Sawda (RA)", "Hazrat Hafsa (RA)", "Hazrat Maymuna (RA)", "Hazrat Umm Salama (RA)"], "answer": 0, "explanation": "Hazrat Sawda (RA) gave her allotted day to Aisha out of love for the Prophet (PBUH) and Aisha."},
    {"q": "Which wife of the Prophet (PBUH) was known for memorizing the Quran and kept the first compiled copy after Umar's death?", "options": ["Hazrat Aisha (RA)", "Hazrat Hafsa (RA)", "Hazrat Khadija (RA)", "Hazrat Zainab (RA)"], "answer": 1, "explanation": "Hazrat Hafsa (RA) was entrusted with the original manuscript compiled during Abu Bakr's caliphate."},
    {"q": "When did the Prophet (PBUH) marry Hazrat Khadija (RA)?", "options": ["Before Prophethood (at age 25)", "After Prophethood (at age 40)", "After Hijrah (at age 53)", "At age 30"], "answer": 0, "explanation": "He married her 15 years prior to receiving the first revelation."},
    {"q": "From which Jewish tribe did Hazrat Safiyya (RA) originate?", "options": ["Banu Qaynuqa", "Banu Nadir", "Banu Qurayza", "Banu Mustaliq"], "answer": 1, "explanation": "Her father was the chief of the Banu Nadir tribe."},
    {"q": "Where did the Prophet (PBUH) and Hazrat Khadija (RA) initially reside after their marriage?", "options": ["Madinah", "Taif", "Makkah", "Syria"], "answer": 2, "explanation": "They lived in Makkah for their entire 25-year marriage."},
    {"q": "How many daughters did the Prophet (PBUH) have with Hazrat Khadija (RA)?", "options": ["Two", "Three", "Four", "Five"], "answer": 2, "explanation": "They had four daughters: Zainab, Ruqayyah, Umm Kulthum, and Fatima."},
    {"q": "Which wife survived the Prophet (PBUH) the longest, dying around 61 AH?", "options": ["Hazrat Aisha (RA)", "Hazrat Safiyya (RA)", "Hazrat Umm Salama (RA)", "Hazrat Juwayriya (RA)"], "answer": 2, "explanation": "Hazrat Umm Salama (RA) lived outlived all other wives, dying during Yazid's reign."},
    {"q": "Who took the Prophet (PBUH) to her cousin Waraqa bin Naufal to understand his first revelation?", "options": ["Hazrat Aisha (RA)", "Hazrat Khadija (RA)", "Hazrat Sawda (RA)", "Hazrat Hafsa (RA)"], "answer": 1, "explanation": "Khadija (RA) took him to Waraqa, a Christian scholar, who confirmed his prophethood."},
    {"q": "What was the relation of Hazrat Zaid bin Harithah to Hazrat Zainab bint Jahsh before she married the Prophet (PBUH)?", "options": ["He was her brother", "He was her cousin", "He was her former husband", "He was her father"], "answer": 2, "explanation": "Zaid bin Harithah (the Prophet's adopted son) was previously married to Zainab; they divorced, after which she married the Prophet to abolish the taboo of marrying an adopted son's ex-wife."},
    {"q": "Hazrat Maymuna (RA) died at the exact place where she had been married to the Prophet (PBUH). Where was this?", "options": ["Quba", "Saraf", "Mina", "Arafat"], "answer": 1, "explanation": "She died at Saraf, near Makkah, and was buried there."},
    {"q": "Which wife of the Prophet (PBUH) was extremely tall and heavily built?", "options": ["Hazrat Aisha (RA)", "Hazrat Sawda (RA)", "Hazrat Khadija (RA)", "Hazrat Safiyya (RA)"], "answer": 1, "explanation": "Hazrat Sawda bint Zam'ah (RA) was known to be tall and heavy, such that she struggled to move fast in later years."},
    {"q": "According to Sunni tradition, what was the age of Hazrat Aisha (RA) when she consummated the marriage with the Prophet (PBUH) in Madinah?", "options": ["9", "15", "18", "21"], "answer": 0, "explanation": "Traditional Hadith sources state she was 9 when she moved into the Prophet's household in Madinah."},
    {"q": "Who was the mother of Hazrat Aisha (RA)?", "options": ["Umm Ruman", "Fatima bint Asad", "Asma bint Umais", "Hind bint Utbah"], "answer": 0, "explanation": "Umm Ruman was the wife of Abu Bakr and the mother of Aisha and Abdur-Rahman."},
    {"q": "Which wife was known to have a very fiery/short temper but was quick to repent, according to Aisha (RA)?", "options": ["Hazrat Sawda (RA)", "Hazrat Hafsa (RA)", "Hazrat Zainab bint Jahsh (RA)", "Hazrat Safiyya (RA)"], "answer": 2, "explanation": "Aisha praised Zainab's religious devoutness, saying her only flaw was a quick temper which faded as quickly as it came."},
    {"q": "The verses commanding the wives of the Prophet (PBUH) to observe Hijab (veil) were primarily revealed after the marriage to which wife?", "options": ["Hazrat Zainab bint Jahsh (RA)", "Hazrat Aisha (RA)", "Hazrat Hafsa (RA)", "Hazrat Umm Salama (RA)"], "answer": 0, "explanation": "The verses of Hijab were revealed during the Walima feast of Zainab bint Jahsh."},
    {"q": "Who was the uncle of Hazrat Hafsa (RA) and the brother of Umar (RA) who was martyred at Yamama?", "options": ["Zaid bin al-Khattab", "Abdullah bin Umar", "Abu Ubaidah", "Amr bin al-Aas"], "answer": 0, "explanation": "Zaid bin al-Khattab was the older brother of Umar (RA)."},
    {"q": "The Prophet (PBUH) was passing away when his head was resting on whose lap/chest?", "options": ["Hazrat Ali (RA)", "Hazrat Fatima (RA)", "Hazrat Aisha (RA)", "Hazrat Khadija (RA)"], "answer": 2, "explanation": "He passed away in the arms/lap of Hazrat Aisha (RA)."},
    {"q": "Hazrat Umm Salama's (RA) original name was?", "options": ["Hind bint Abi Umayya", "Ramla bint Abu Sufyan", "Zainab bint Jahsh", "Barrah bint Harith"], "answer": 0, "explanation": "Her name was Hind. 'Umm Salama' was her Kunya (mother of Salama)."},
    {"q": "Which wife of the Prophet (PBUH) was buried in Jannat al-Mu'alla in Makkah?", "options": ["Hazrat Aisha (RA)", "Hazrat Khadija (RA)", "Hazrat Sawda (RA)", "Hazrat Hafsa (RA)"], "answer": 1, "explanation": "Khadija (RA) passed away in Makkah before the Hijrah and is buried there."},
    {"q": "Apart from Khadija and Maymuna, all other wives are buried where?", "options": ["Jannat al-Mu'alla", "Jannat al-Baqi", "Mount Uhud", "Dome of the Rock"], "answer": 1, "explanation": "The rest of the Mothers of the Believers are buried in Jannat al-Baqi in Madinah."},
    {"q": "Which wife's dowry (Mahr) was her very freedom/manumission from slavery?", "options": ["Hazrat Zainab (RA)", "Hazrat Safiyya (RA)", "Hazrat Khadija (RA)", "Hazrat Aisha (RA)"], "answer": 1, "explanation": "The Prophet (PBUH) freed Safiyya (and similarly Juwayriya) and made their emancipation their Mahr."},
    {"q": "Who used to bring food to the Prophet (PBUH) and Hazrat Abu Bakr (RA) during their stay in the Cave of Thawr?", "options": ["Asma bint Abu Bakr", "Aisha bint Abu Bakr", "Khadija bint Khuwaylid", "Fatimah bint Muhammad"], "answer": 0, "explanation": "Asma, Aisha's older sister, secretly brought them provisions."},
    {"q": "Hazrat Khadija (RA) traded with the wealth of others and shared the profits. This type of Islamic business contract is called?", "options": ["Musharakah", "Mudarabah", "Murabahah", "Ijarah"], "answer": 1, "explanation": "Mudarabah is a partnership where one supplies capital and the other supplies labor/management."},
    {"q": "During the Prophet’s (PBUH) marriage to Hazrat Khadija (RA), did he take any other wives?", "options": ["Yes, one", "Yes, two", "Yes, multiple", "No, none"], "answer": 3, "explanation": "The Prophet (PBUH) remained monogamous during the 25 years he was married to Khadija (RA)."},
    {"q": "Which wife was known as 'Tayyiba' and 'Tahirah' (The Pure One) even during the pre-Islamic days of Ignorance (Jahiliyyah)?", "options": ["Hazrat Khadija (RA)", "Hazrat Aisha (RA)", "Hazrat Sawda (RA)", "Hazrat Maymuna (RA)"], "answer": 0, "explanation": "Khadija was known as Tahirah due to her impeccable character even before Islam."},
    {"q": "In which Hijri year did the marriage between the Prophet (PBUH) and Hazrat Aisha (RA) take place?", "options": ["1 AH", "2 AH", "3 AH", "4 AH"], "answer": 1, "explanation": "The marriage contract was done in Makkah, but consummated in Madinah around 2 AH after the Battle of Badr."},
    {"q": "When Zainab bint Jahsh (RA) received her stipend during Umar's caliphate, what did she do with it?", "options": ["Saved it to build a mosque", "Gave it all away to the poor immediately", "Bought jewelry", " invested it in trade"], "answer": 1, "explanation": "She was extremely charitable and distributed all her wealth to the needy as soon as she received it."},
    {"q": "The Prophet (PBUH) said 'the excellence of 'Aisha over other women is like the excellence of _______ over other foods'.", "options": ["Tharid", "Honey", "Dates", "Milk"], "answer": 0, "explanation": "Tharid was a popular Arab dish of bread and meat broth, considered superior food at the time."},
    {"q": "Who was the father of Hazrat Khadija (RA)?", "options": ["Khuwaylid ibn Asad", "Abu Talib", "Asad ibn Hashim", "Mut'im ibn Adi"], "answer": 0, "explanation": "She was Khadija bint Khuwaylid."}
]

idx1, subidx1 = get_category_idx("World Islamic Empires")
idx2, subidx2 = get_category_idx("Islamic Sharia Law")
idx3, subidx3 = get_category_idx("Prophet Wife")

# Append the questions
quiz_data[idx1]["subcategories"][subidx1]["questions"].extend(questions_empires)
quiz_data[idx2]["subcategories"][subidx2]["questions"].extend(questions_sharia)
quiz_data[idx3]["subcategories"][subidx3]["questions"].extend(questions_wife)

# Write back
new_content = 'const mainQuizData = ' + json.dumps(quiz_data, indent=4) + ';\n'

# Replace original content from json_start to json_end
final_content = content[:content.find('const mainQuizData = ')] + new_content

with open('c:/Users/AlFurqan/Desktop/ahmedsaeedss.github.io-main/data.js', 'w', encoding='utf-8') as f:
    f.write(final_content)

print(f"Added {len(questions_empires)} questions to 'World Islamic Empires'")
print(f"Added {len(questions_sharia)} questions to 'Islamic Sharia Law'")
print(f"Added {len(questions_wife)} questions to 'Prophet Wife'")
print("Done.")
